### PR TITLE
Docker adjustments and small fixes

### PR DESCRIPTION
**Pull request by ThePhaseless**
I wanted to use this script, but I saw that it was made just to work with docker, I've made some adjustments i.e. config generation when using it with docker, updated README and reformatted and fixed some types.

### CODE REVIEW

**Review by Feramance — DISMISSED** [review]
Please uncomment the logging section in the compose as without it you will get to a point where docker returns an error and the log files become GBs in size

**Comment by Feramance** [comment]
Please also fix pre-commit.ci issues

**Comment by Feramance** [comment]
Also just noticed, you set the gen_config database file to /config/arr.db whereas in the compose you set the path to /databases/arr.db

**Comment by ThePhaseless** [comment]
Ah yes, will fix this tommorow

**Comment by Feramance** [comment]
Once ready I'll be merging and releasing as a minor update

**Review by Feramance — APPROVED** [review]

**Pull request merged**
